// UK trades / services vocabulary used for autocomplete suggestions in the
// trader business profile ("Services offered"). Purely a suggestion source —
// traders can always type a custom service that isn't listed here.
// Kept consistent with the main trade categories the API exposes.

export const UK_SERVICES: string[] = [
  // Plumbing & heating
  "Plumbing",
  "Emergency plumbing",
  "Boiler installation",
  "Boiler servicing",
  "Boiler repair",
  "Central heating installation",
  "Radiator installation",
  "Underfloor heating",
  "Gas safety checks",
  "Gas appliance installation",
  "Bathroom installation",
  "Bathroom fitting",
  "Shower installation",
  "Wet room installation",
  "Leak detection",
  "Drain unblocking",
  "Pipework repairs",
  "Water tank installation",
  "Power flushing",
  "Heat pump installation",

  // Electrical
  "Electrical installation",
  "Electrical rewiring",
  "Fuse board replacement",
  "Consumer unit upgrades",
  "Electrical testing & inspection",
  "EICR certificates",
  "PAT testing",
  "Lighting installation",
  "Outdoor lighting",
  "Socket installation",
  "EV charger installation",
  "Smart home installation",
  "Security alarm installation",
  "CCTV installation",
  "Smoke alarm installation",
  "Electric shower installation",
  "Emergency electrician",

  // Building & construction
  "General building",
  "House extensions",
  "Loft conversions",
  "Garage conversions",
  "Basement conversions",
  "New builds",
  "Renovations",
  "Structural work",
  "Underpinning",
  "Bricklaying",
  "Blockwork",
  "Repointing",
  "Stonework",
  "Chimney repairs",
  "Foundations",
  "Groundworks",
  "Concreting",
  "Steel beam installation",
  "Damp proofing",
  "Timber treatment",
  "Insulation installation",

  // Roofing
  "Roof repairs",
  "Roof replacement",
  "Flat roofing",
  "Pitched roofing",
  "Tile & slate roofing",
  "Guttering installation",
  "Gutter cleaning",
  "Fascias & soffits",
  "Chimney flashing",
  "Roof inspections",
  "Leadwork",
  "EPDM rubber roofing",

  // Carpentry & joinery
  "Carpentry",
  "Joinery",
  "Kitchen fitting",
  "Fitted wardrobes",
  "Bespoke furniture",
  "Door hanging",
  "Skirting & architrave",
  "Staircase installation",
  "Timber framing",
  "Decking installation",
  "Shelving & storage",
  "Window installation",
  "Sash window restoration",

  // Painting & decorating
  "Painting & decorating",
  "Interior painting",
  "Exterior painting",
  "Wallpapering",
  "Plaster skimming",
  "Spray painting",
  "Mist coating",

  // Plastering
  "Plastering",
  "Rendering",
  "Dry lining",
  "Coving installation",
  "Artex removal",
  "Screeding",
  "Venetian plastering",
  "External wall insulation",

  // Flooring & tiling
  "Tiling",
  "Bathroom tiling",
  "Kitchen tiling",
  "Floor tiling",
  "Flooring installation",
  "Laminate flooring",
  "Hardwood flooring",
  "Engineered wood flooring",
  "Vinyl & LVT flooring",
  "Carpet fitting",
  "Floor sanding",
  "Resin flooring",

  // Gardening & landscaping
  "Gardening",
  "Garden maintenance",
  "Landscaping",
  "Garden design",
  "Lawn care",
  "Turfing",
  "Artificial grass installation",
  "Hedge trimming",
  "Tree surgery",
  "Tree felling",
  "Stump removal",
  "Fencing",
  "Gate installation",
  "Patio installation",
  "Paving",
  "Driveways",
  "Block paving",
  "Resin driveways",
  "Garden walls",
  "Pergolas & garden rooms",
  "Shed installation",
  "Pressure washing",

  // Windows, doors & glazing
  "Double glazing",
  "Window repairs",
  "UPVC windows & doors",
  "Composite doors",
  "Bifold doors",
  "Conservatories",
  "Glazing repairs",
  "Secondary glazing",
  "Misted glass replacement",

  // Locks & security
  "Locksmith services",
  "Lock replacement",
  "Emergency lockout",
  "UPVC door lock repairs",
  "Safe installation",

  // Cleaning & clearance
  "Domestic cleaning",
  "Deep cleaning",
  "End of tenancy cleaning",
  "Carpet cleaning",
  "Oven cleaning",
  "Window cleaning",
  "House clearance",
  "Garden clearance",
  "Rubbish removal",

  // Removals & handyman
  "Handyman services",
  "Furniture assembly",
  "TV wall mounting",
  "Picture & mirror hanging",
  "Curtain & blind fitting",
  "Removals",
  "Man & van",

  // Appliances & other
  "Appliance installation",
  "Appliance repairs",
  "Washing machine repairs",
  "Cooker installation",
  "Air conditioning installation",
  "Ventilation installation",
  "Solar panel installation",
  "Pest control",
  "Scaffolding",
  "Skip hire",
  "Asbestos removal",
  "Chimney sweeping",
  "Aerial & satellite installation",
  "Bathroom design",
  "Kitchen design",
  "Architectural services",
  "Surveying",
];
