import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import tradersRouter from "./traders";
import profileRouter from "./profile";
import subscriptionsRouter from "./subscriptions";
import savedTradersRouter from "./saved-traders";
import enquiriesRouter from "./enquiries";
import categoriesRouter from "./categories";
import contactRouter from "./contact";
import traderPhoneRouter from "./trader-phone";
import traderDocumentsRouter from "./trader-documents";
import customerUploadsRouter from "./customer-uploads";
import reviewsRouter from "./reviews";
import conversationsRouter from "./conversations";
import pushTokensRouter from "./push-tokens";
import adminRouter from "./admin";
import emailUnsubscribeRouter from "./email-unsubscribe";
import companiesHouseRouter from "./companies-house";
import promoRouter from "./promo";
import accountDeletionRouter from "./account-deletion";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(tradersRouter);
router.use(profileRouter);
router.use(subscriptionsRouter);
router.use(savedTradersRouter);
router.use(enquiriesRouter);
router.use(categoriesRouter);
router.use(contactRouter);
router.use(traderPhoneRouter);
router.use(traderDocumentsRouter);
router.use(customerUploadsRouter);
router.use(reviewsRouter);
router.use(conversationsRouter);
router.use(pushTokensRouter);
router.use(adminRouter);
router.use(emailUnsubscribeRouter);
router.use(companiesHouseRouter);
router.use(promoRouter);
router.use(accountDeletionRouter);

export default router;
