// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/admin/AdminDashboardRefined.tsx": () => import("../components/mockups/admin/AdminDashboardRefined.tsx"),
  "./components/mockups/mobile/MobileHomeRefined.tsx": () => import("../components/mockups/mobile/MobileHomeRefined.tsx")
};
